USE [snnb_FO]
GO

/****** Object:  Table [dbo].[SpecNetGroups]    Script Date: 25Nov2022 8:18:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SpecNetGroups](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[UnitId] [int] NOT NULL,

 CONSTRAINT [PK_SpecNetGroups] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

