USE [master]
GO

/****** Object:  Database [snnb_FO]    Script Date: 20/12/2022 04:33:42 ******/
CREATE DATABASE [snnb_FO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'snnb_FO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\snnb_FO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [memory_optimized_filegroup_0] CONTAINS MEMORY_OPTIMIZED_DATA  DEFAULT
( NAME = N'memory_optimized_file_836562713', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\memory_optimized_file_836562713' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'snnb_FO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\snnb_FO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [snnb_FO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [snnb_FO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [snnb_FO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [snnb_FO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [snnb_FO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [snnb_FO] SET ARITHABORT OFF 
GO

ALTER DATABASE [snnb_FO] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [snnb_FO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [snnb_FO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [snnb_FO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [snnb_FO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [snnb_FO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [snnb_FO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [snnb_FO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [snnb_FO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [snnb_FO] SET  ENABLE_BROKER 
GO

ALTER DATABASE [snnb_FO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [snnb_FO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [snnb_FO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [snnb_FO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [snnb_FO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [snnb_FO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [snnb_FO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [snnb_FO] SET RECOVERY FULL 
GO

ALTER DATABASE [snnb_FO] SET  MULTI_USER 
GO

ALTER DATABASE [snnb_FO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [snnb_FO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [snnb_FO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [snnb_FO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [snnb_FO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [snnb_FO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [snnb_FO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [snnb_FO] SET  READ_WRITE 
GO

